// no need of the function name...(in invoked function....)
// In arrow function have not need to function name....
// In anonymous have also not need to function name....
// syntax);-var hello=()=>console.log("hello neetu"){}

// // 1)))...Invoked func,...
(function (a,b) {
    console.log(a+b);
})(23,2)

// 2nd method to solve functions....
// ARROW FUNCTION....
var num=(a,b)=>console.log(a+b);{
}
num(23,32)

// 3rd type to define....
// ANONYMOUS FUNCTION.....
var a=function (a,b) {
    console.log(a+b);
}
(33,4)
